steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/cloudrun-postgres-test',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'cloudrun-postgres-test',
        '--image', 'gcr.io/$PROJECT_ID/cloudrun-postgres-test',
        '--region', '${_REGION}',
        '--platform', 'managed',
        '--add-cloudsql-instances', '${_INSTANCE_CONNECTION_NAME}',
        '--service-account', '${_CLOUD_RUN_SA}',
        '--allow-unauthenticated',
        '--set-env-vars',
        'DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},INSTANCE_UNIX_SOCKET=${_INSTANCE_UNIX_SOCKET}'
      ]

images:
  - 'gcr.io/$PROJECT_ID/cloudrun-postgres-test'

substitutions:
  _REGION: '${_REGION}'
  _INSTANCE_CONNECTION_NAME: '${_INSTANCE_CONNECTION_NAME}'
  _CLOUD_RUN_SA: '${_CLOUD_RUN_SA}'
  _DB_USER: '${_DB_USER}'
  _DB_PASS: '${_DB_PASS}'
  _DB_NAME: '${_DB_NAME}'
  _INSTANCE_UNIX_SOCKET: '${_INSTANCE_UNIX_SOCKET}'
